[book]
authors = ["Sébastien Wilmet", "Gerson Benavides"]
language = "es"
multilingual = false
src = "src"
title = "La plataforma de desarrollo GLib/GTK"

[output.html]
git-repository-url = "https://github.com/gersonbenavides/glib-gtk-libro"
git-repository-icon = "fa-github"
site-url = "/glib-gtk-libro/"
additional-css = ["./src/assets/css/custom.css"]
additional-js = ["./src/assets/js/refs.js"]

[build]
build-dir = "book"
create-missing = false